version: '3.3'
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "${APP_PORT}:${NGINX_PORT}"
        environment:
            - NGINX_HOST=${NGINX_HOST}
            - NGINX_PORT=${NGINX_PORT}
            - APP_PATH=${APP_PATH}
        command: /bin/bash -c "envsubst '$${NGINX_HOST} $${NGINX_PORT} $${APP_PATH}'< /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        volumes:
            - ./docker/nginx/core:/etc/nginx/conf.d/
            - ./docker/nginx/logs:/var/log/nginx/
            - ./www:/var/www/
        links:
            - php
            - db    
        depends_on:
            - php
        networks:
            - internal

    db:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3306:3306"
        container_name: ${DB_HOST}
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASS}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASS}
        volumes:
            - ./docker/db:/var/lib/mysql
        networks:
            - internal

    php:
        build: ./docker/php
        container_name: php-fpm
        volumes:
            - ./www:/var/www
        links:
            - db
        depends_on:
            - db
        networks:
            - internal

    adminer:
        image: adminer
        container_name: adminer
        restart: always
        ports:
            - 8081:8080
        links:
            - db
        networks:
            - internal

networks:
    internal:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.220.0/28
