version: '3.3'
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./docker/nginx/core:/etc/nginx/conf.d/
            - ./docker/nginx/logs:/var/log/nginx/
            - ./www:/var/www/
        links:
            - php
            - db

    db:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3306:3306"
        container_name: db
        environment:
            - MYSQL_ROOT_PASSWORD=mypassword
            - MYSQL_DATABASE=test
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
        volumes:
            - ./docker/db:/var/lib/mysql


    php:
        build: ./docker/php
        container_name: php-fpm
        volumes:
            - ./www:/var/www
        links:
            - db

    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080
        links:
            - db